### PR TITLE
added new site

### PR DESCRIPTION
**Pull request by kalisnetwork**

### CODE REVIEW

**Comment by juxtopposed** [comment]
I think the database file here is older. The live site includes the CodePen links you submitted. The Diagram one is nice though.

**Comment by kalisnetwork** [comment]
I was mistakenly updated hackernoon codepen link just to see and i have pushed with new added site, My bad

**Comment by kalisnetwork** [comment]
Should I pull again, I have resolved the conflicts but I don't know what happened again deployment failed.

**Comment by juxtopposed** [comment]
not really sure why, but I just made the changes on the site.

**Pull request merged**
