### PR TITLE
demonstrate simplicity of anchors vs buttons

### PR DESCRIPTION
**Pull request by p5quared**
- replace button with anchor
- I removed a lot of logic that does not appear to be doing anything; correct me if I am wrong here.

### CODE REVIEW

**Comment by p5quared** [comment]
Referenced by #22

**Comment by juxtopposed** [comment]
Hey there. The parts you deleted have to do with routing and all that, mostly to quickly switch between categories.

By the way, I'm still producing what you described in #22.
Selecting different modals and going back still produces the same result. 

Also worth noting in #6, the ability to move back and forth via left and right arrow was introduced but of course that's no good for mobile. I'm happy to resolve this if you have any suggestions.

**Comment by p5quared** [comment]
I'll look at this a little closer.

I've also posted a video showing what happens when I navigate in #22.

With regard to #6, what do you mean when you say resolve?

**Comment by mikikiv** [comment]
#6 was specific to modals being able to move left and right on examples with the keyboard. This PR looks like it removes a supposed similar functionality for the categories which I would agree doesn't appear to have any way for it to actually work. 

**The biggest issue here is that these changes remove the ability for a user to see the menu of categories in mobile.**

I think a button is preferred (or at least is what I would use) for category selection since using an anchor reloads the full page. Maybe this is related to #22 but the issue still occurs and even occurs between category navigation without the modal. 

If there was something to cleanup, it might be this one line where I can't figure out any way that a keydown would be able to select a specific category; unless there was like a command bar or something.
CleanShot 2023-11-16 at 15 45 24

**Pull request closed without merging**
